### PR TITLE
3.8 upgrade

### PR DESCRIPTION
**Pull request by obinnaEmelumadu**
I have found that this particular module meets my needs and I wish to upgrade it to use the 3.8 version of spine. 
I have also noticed that the @rayxuln has created a new project that also meets those needs, but doesn't have some of the features I wish to use.

@scottkunkel since you worked on both of these projects, I wish to know 

1. Is upgrading to 3.8 as simple as just replacing the existing source files?
2. are there any bugs/lessons learned you can share that would help with making this module ore stable>

### CODE REVIEW

**Comment by scottkunkel** [comment]
> I have found that this particular module meets my needs and I wish to upgrade it to use the 3.8 version of spine.
> I have also noticed that the @rayxuln has created a new project that also meets those needs, but doesn't have some of the features I wish to use.
> 
> @scottkunkel since you worked on both of these projects, I wish to know
> 
> 1. Is upgrading to 3.8 as simple as just replacing the existing source files?
> 2. are there any bugs/lessons learned you can share that would help with making this module ore stable>

Thanks for committing back your changes.

1 - I haven't looked at 3.8, so I am not sure what's new. It's more likely adding features, so dropping the new files should work, unless they changed part of the API.
2 - The biggest contribution I did was streamlining the code. The original code was doing a lot of creating and tearing down objects instead of reusing the existing ones, making the code very slow. I have not found any bugs while using my code but I am only one tester.

Regards,
Thomas

**Comment by obinnaEmelumadu** [comment]
YO, DONT MERGE THIS PR!!
I found a bug while building:

```
[ 44%] Compiling ==> modules\spine\spine_batcher.cpp
[ 44%] Compiling ==> modules\spine\spine_slot.cpp
register_types.cpp
spine_slot.cpp
spine_batcher.cpp
spine.cpp
D:\Godot Source\godot\modules\spine\include\spine/extension.h(102): warning C4005: 'ABS': macro redefinition
D:\Godot Source\godot\core/typedefs.h(115): note: see previous definition of 'ABS'
D:\Godot Source\godot\modules\spine\include\spine/extension.h(127): warning C4005: 'CLAMP': macro redefinition
D:\Godot Source\godot\core/typedefs.h(133): note: see previous definition of 'CLAMP'
D:\Godot Source\godot\modules\spine\include\spine/extension.h(102): warning C4005: 'ABS': macro redefinition
D:\Godot Source\godot\core/typedefs.h(115): note: see previous definition of 'ABS'
D:\Godot Source\godot\modules\spine\include\spine/extension.h(127): warning C4005: 'CLAMP': macro redefinition
D:\Godot Source\godot\core/typedefs.h(133): note: see previous definition of 'CLAMP'
modules\spine\spine.cpp(1122): error C3861: 'spSkin_addAttachments': identifier not found
modules\spine\spine.cpp(1146): error C3861: 'spSkeleton_getBone': identifier not found
scons: *** [modules\spine\spine.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by obinnaEmelumadu** [comment]
@scottkunkel It looks like some of the functions have changed or have been removed

@chanon @Geequlim may join if interested

**Comment by scottkunkel** [comment]
hey, I was not looking right. The git you used is an old implementation
that I personally have not used forever.

This is much more flexible and faster:
https://github.com/scottkunkel/spine_runtime

**Pull request merged**
